### ISSUE TITLE
Container startup loads 1GB checkpoint file

### ISSUE THREAD

**Issue by matthias-mayr** [HashimHS/pose-estimation-service#3]
Right now every container startup loads a 1GB file:
```
UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1695392020201/work/aten/src/ATen/native/TensorShape.cpp:3526.)
final text_encoder_type: bert-base-uncased
tokenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48.0/48.0 [00:00<00:00, 596kB/s]
Model loaded from /home/ubuntu/.cache/huggingface/hub/models--ShilongLiu--GroundingDINO/snapshots/a94c9b567a2a374598f05c584e96798a170c56fb/groundingdino_swinb_cogcoor.pth 
 => _IncompatibleKeys(missing_keys=[], unexpected_keys=['label_enc.weight', 'bert.embeddings.position_ids'])
Downloading: "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_l_0b3195.pth" to /home/ubuntu/.cache/torch/hub/checkpoints/sam_vit_l_0b3195.pth
 16%|██████████████████████▎                                                                                                                      | 188M/1.16G [00:04<00:23, 45.2MB/s]
```

We can endure that in the office, but in case one wants to work at a location where the internet is worse, that would be an issue.

Is it possible to move that into the container build?

**Comment by HashimHS** [comment]
This file is basically the model weights for SAM. Can be downloaded from the link:
https://dl.fbaipublicfiles.com/segment_anything/sam_vit_l_0b3195.pth

It is only downloaded once when you set up the container. But I can include the weights next to the cache file if necessary. The only caveat is that github does not allow you to upload large files.

Kind regards,
Hashim
________________________________
From: Matthias Mayr ***@***.***>
Sent: Thursday, October 24, 2024 3:32 PM
To: HashimHS/pose-estimation-service ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [HashimHS/pose-estimation-service] Container startup loads 1GB checkpoint file (Issue #3)


Right now every container startup loads a 1GB file:

UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1695392020201/work/aten/src/ATen/native/TensorShape.cpp:3526.)
final text_encoder_type: bert-base-uncased
tokenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48.0/48.0 [00:00<00:00, 596kB/s]
Model loaded from /home/ubuntu/.cache/huggingface/hub/models--ShilongLiu--GroundingDINO/snapshots/a94c9b567a2a374598f05c584e96798a170c56fb/groundingdino_swinb_cogcoor.pth
 => _IncompatibleKeys(missing_keys=[], unexpected_keys=['label_enc.weight', 'bert.embeddings.position_ids'])
Downloading: "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_l_0b3195.pth" to /home/ubuntu/.cache/torch/hub/checkpoints/sam_vit_l_0b3195.pth
 16%|██████████████████████▎                                                                                                                      | 188M/1.16G [00:04<00:23, 45.2MB/s]


We can endure that in the office, but in case one wants to work at a location where the internet is worse, that would be an issue.

Is it possible to move that into the container build?

**Comment by matthias-mayr** [comment]
Not as nice as a one-time download, but an alternative would be to just include the download into the container build procedure. If it will always be available, it does not need to be hosted anywhere then

**Comment by HashimHS** [comment]
Sure, I will add it to the docker build then.

Kind regards
Hashim Ismail

**Comment by HashimHS** [comment]
I have modified the Dockerbuild file so that all files are downloaded automatically.
